---
title: "completed_mooc"
author: "Ada Lee"
date: "April 3, 2016"
output: html_document
---

## Coursera

### Speciliazations

1. [Fundamental of Computing](https://www.coursera.org/account/accomplishments/specialization/YJVCLCWCZQQT)

* [An Introduction to Interactive Programming in Python (Part 1)](https://www.coursera.org/account/accomplishments/verify/X3RG4NTKDS)
* [An Introduction to Interactive Programming in Python (Part 2)](https://www.coursera.org/account/accomplishments/verify/2YGPHUBHTN)
* [Principles of Computing (Part 1)](https://www.coursera.org/account/accomplishments/verify/UQGFS8734A)
* [Principles of Computing (Part 2)](https://www.coursera.org/account/accomplishments/verify/SAAKLAL6H2)
* [Algorithmic Thinking (Part 1)](https://www.coursera.org/account/accomplishments/verify/2ADRCEWH39)
* [Algorithmic Thinking (Part 2)](https://www.coursera.org/account/accomplishments/verify/7MSBZJX8M7)
* [The Fundamentals of Computing Specialization Capstone Exam](https://www.coursera.org/account/accomplishments/verify/C9NTQX2TD6)

2. [Data Science](https://www.coursera.org/account/accomplishments/specialization/YJVCLCWCZQQT)

* [The Data Scientist’s Toolbox](https://www.coursera.org/account/accomplishments/verify/SJ85G59PN2)
* [R programming](https://www.coursera.org/account/accomplishments/verify/62FSFTFH96)
* [Getting and Cleaning Data](https://www.coursera.org/account/accomplishments/verify/V3F4LGRPCE)
* [Exploratory Data Analysis](https://www.coursera.org/account/accomplishments/verify/9MZSXKDV9C)
* [Reproducible Research](https://www.coursera.org/account/accomplishments/verify/27BYK74G57)
* [Statistical Inference](https://www.coursera.org/account/accomplishments/verify/CT68RWWLL3)
* [Regression Models](https://www.coursera.org/account/accomplishments/verify/VDHQCF29FR)
* [Practical Machine Learning](https://www.coursera.org/account/accomplishments/verify/D67TYBC6T8)
* [Developing Data Products](https://www.coursera.org/account/accomplishments/verify/3HBEV8NESM)
* [Data Science Capstone](https://www.coursera.org/account/accomplishments/verify/X47JJ9XE4J)

3. Data Mining

* [Pattern Discovery in Data Mining](https://www.coursera.org/account/accomplishments/records/CjCcFvPUzkWYZ5KR)
* [Cluster Analysis in Data Mining](https://www.coursera.org/account/accomplishments/records/2yVp45HW5wN65pmN)
* [Data Visualization](https://www.coursera.org/account/accomplishments/records/vhXZAuj2wp56PTBY)

4. Python for Everybody

* [Programming for Everybody](https://www.coursera.org/account/accomplishments/records/N6U8ZG8VSY63)
* [Python Data Structures](https://www.coursera.org/account/accomplishments/records/XEGA8JNJLWUX)
* [Using Python to Access Web Data](https://www.coursera.org/account/accomplishments/records/V2Y6A77AY76J)
* [Using Databases with Python](https://www.coursera.org/account/accomplishments/records/EJ8FS9JNAV3L)

5. Machine Learning

* [Machine Learning Foundations: A Case Study Approach](https://www.coursera.org/account/accomplishments/records/YA7NQTVPMY4J)
* [Machine Learning: Regression](https://www.coursera.org/account/accomplishments/records/C8F5G46NE4VJ)
* [Machine Learning: Classification](https://www.coursera.org/account/accomplishments/records/5AU582478FSC)

## Single Courses

1. [Algorithms: Design and Analysis, Part 1](https://www.coursera.org/maestro/api/certificate/get_certificate?course_id=971469)
2. [Algorithms: Design and Analysis, Part 2](https://www.coursera.org/maestro/api/certificate/get_certificate?course_id=972334)
3. [Crafting an Effective Writer: Tools of the Trade (Fundamental English Writing)](https://www.coursera.org/maestro/api/certificate/get_certificate?course_id=973428)
4. [The Power of Microeconomics: Economic Principles in the Real World
](https://www.coursera.org/account/accomplishments/records/N5Tt5YJMgWu2G6DT)
5. [Introduction to Programming with MATLAB
](https://www.coursera.org/account/accomplishments/records/GxBxmHBW44CXDeDQ)
6. [Think Again: How to Reason and Argue](https://www.coursera.org/account/accomplishments/records/RQNNw37STjxm94nK)
7. [Introduction to Natural Language Processing
](https://www.coursera.org/account/accomplishments/records/KS23NjZ3buWLxgAd)
8. [Internet History, Technology, and Security](https://www.coursera.org/account/accomplishments/records/R68PUE8E6SUJ)

## Edx

## Udacity