---
title: "我的mooc之路"
author: "李丽丽"
date: "March 31, 2016"
output: html_document
---

最开始接触mooc是从网易开始的，我下载了哈佛大学的公平课程以及耶鲁大学的死亡课程，然后试着去听听这些课。后来又用谷歌搜索，并大概听了一些计算机方面的课程，比如操作系统、计算机网络、机器学习以及数据库，我做了很多笔记，但是由于没有细思内容，也没有做作业，因此效果并不好。Coursera平台上，每门课都有开课时间，作业都有期限，最后也会有完成证书，于是我决定开始尝试认真地完成一门课。大学的时候我有段时间周一到周五每天早晨在400米操场跑步10到14圈，我的想法很简单，就是我能跑1圈就能跑10圈，我把这种思维方式也用到mooc里，我的想法是先尝试完成一门课，然后复现99次，就能完成100门了。最后我选择了斯坦福大学的算法课程，选择这门课一是因为斯坦福大学的名气，二是因为大学的时候我学过一学期的数据结构，所以有一点基础，同时也可以体验一下国外的大学的教学是什么样的。当时的我对这种线上教育一无所知，也不清楚应该把分数目标定在哪里，所以我是希望把第一门课成绩作为后续课程的目标底线。当时这门课对我的难度还是非常大的，以最简单的排序算法为例，虽然数据结构里面有学排序，但是那时候的我仅仅把自己写的排序算法用于非常小的数据量，因而不会有文件读取，解析的过程，更不会有因为大量运算而暴露出以及意识到程序效能的问题。那时候14年5月份离大学结束结束只有两个月了，因为没有别的课程，所以我有非常多的时间。因为我是数学专业的，所以对matlab比较熟悉，就用matlab来完成作业，我的程序跑得非常慢，也总是有很多的错误，那时候我感觉非常差，但是我不断地告诉自己要坚持，不惜时间代价，第一门课成绩一定要尽量高，要容忍自己差劲，因为这门课编程只是提交最后计算结果，所以我告诉自己慢没有关系，只要最后结果算出来就可以了。五月底的时候我必须要考虑自己的工作了，那时候我想着去一线城市，我并没有多少资讯来源，但是我是一个初出茅庐不怕虎的人，简单地选择了GDP第一的上海，在网上投了几份上海的IT方面简历，收到面试通知后就独自来到人生地不熟上海了。很幸运的是我的第一份面试就拿到了offer，又去了两家没有要我，就不想再面试了。开始实习，我的课程继续上着，论坛里面别人跑几秒的程序我要跑几分钟甚至几个小时，我当时还一度以为会不会是我的电脑有问题。最后这门课我的编程题全对，选择题错了一些，拿了92.5分。拿下了第一门课后，我很矛盾，即有了一点信心，又不明白我的程序为什么跑这么慢，因为明明我写的程序算法复杂度跟教授讲的一样，我没有人可以问，只好以90分以上为目标在业余时间继续我的学习，很快我发现可以拿到100分，我的目标分数就提高了。到今天为止我完成了Course上的35门课程,当了两门课助教，作为Coursera中国区top user接受了Coursera中国市场部总负责人半小时的电话访谈。

在长达一年的时间里我只尝试Coursera的课程，然而我发现有些我想上的课程一直没有，所以我不太确定是不是要等着，我和一个同事交流后，他觉得不应该等。比如我想学点Linux命令，Coursera上并没有，我发现Edx上有，于是就在Edx上学了第一门课Linux入门，至今为止我完成Edx上5门课，最喜欢的是Berkeley的两门Spark课程。

我渐渐开始对数据分析感兴趣，希望有用Python讲的数据科学系列课程，然而我只找到Coursera上的用R讲的数据科学系列课程，所以就先学着这个。偶然得知MongoDB是新兴的no-sql数据库，于是我在网上搜索学习资料，发现MongoDB University,就在上面学了两门MongoDB的课程，一门是MongoDB,一门是讲MongoDB python API的。学完这两门课我发现还有一门Data Wrangling with MongoDB,可是这门课不在MongoDB University上，是在[Udacity上](www.udacity.com)的，Udacity就这样开始进入我的生活，我发现这门课的质量非常不错，也有许多编程小练习来巩固知识，又发现这门课是在数据分析纳米学位里，这不就是我寻找的用Python的数据分析系列课程吗？MongoDB的这门课让我对Udacity的课程质量留下了非常好的印象，也对其他课程的质量有了信心，所以我打算把整个数据分析纳米学位学完。我特别喜欢这样打包的课程，因为前期我选择课程的时候就发现很多课程都是入门的，却很少有课程是深入的，因此我特别希望有这种打包的课程，这样我就可以系统地慢慢地提高自己的能力，也不会在大量的课程前迷失。因为学费是美元计的，我为了付学费专门申请了一个visa信用卡，等待信用卡审核批准期间我非常忐忑，经常在银行信用卡微信公众号里查询是否通过，因为支付学费是完成纳米课程的必要条件，好在最后审核通过，我非常开心。学费每个月两百美元，一年内学完可以退一半的学费。最吸引我的是项目有专人批改并提出改进意见，如此反复，直到你的项目满足所有的要求。Coursera上的项目是互评的，感觉差了很多，而且没有改进的过程。就这样我继续着自己死扛的精神看完一门门视频，复习代码，不断地改进每一个项目，最终完成了数据分析纳米课程7门课。项目对我来说还是很有挑战性的，但是又是通过努力可以完成的。项目写累了我有时候会先提交，等着项目审查意见，并读这些意见，让自己写得更好，同时也是把一个大项目分割成两个阶段以减小难度。有的的审查都非常快，出门散步一个小时，回来就能看到结果了，最长的也有等待四五天的，总之比官方承诺的两周时间短很多。因为当时Udacity还未专门进入中国市场，所以项目都是用英文写的，我努力地用我有限的词汇量去表达我的意思，最终被以英语为母语或者英语水平达到母语的人理解，感觉还不错。要毕业需要护照认证身份，中国地区只支持护照，而我当时并没有护照，我发邮件问，他们就给我安排了人工审核，于是2015年12月29日早上七点我就和Udacity教练视频交流，她用英语问了我一些项目的东西，还问我对Udacity的建议，我也用我蹩脚的口语去回答。教练问我我为什么学习这个纳米课程，我说我是一个信仰终身学习的人。远程视频结束后我就获得了Udacity数据分析纳米学位，我想这就是我2015年送给未来的最好的礼物吧。

从2014年5月份正式开始学习mooc,至今也快两年了，我完成了Coursera上35门课，Edx上5门课，MongoDB University 2门课，Udacity 7门课， 总共49门课，我的大部分完成课程都可以在[领英](https://cn.linkedin.com/in/adalee2future)上可以看到。想起最初的目标，我也完成了一半，而我的mooc之路还会继续。